### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by robbyoconnor**
This updates dependencies -- handlebars was insecure.

### CODE REVIEW

**Comment by kriswill** [comment]
LGTM

**Comment by robbyoconnor** [comment]
Did i break the build?

**Comment by kriswill** [comment]
@robbyoconnor looks like linting  errors.  If you want to fix them up that'd be great!  :+1:

**Comment by robbyoconnor** [comment]
This did break the build briefly...but now it's linting errors

--Rob

**Comment by robbyoconnor** [comment]
Hi,

Robert O'Connor invited you to LinkedIn.
Join now to connect with Robert and the rest of your professional world.

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67ocn-c5&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=8ST1cWnq&invitationId=6130897028047257601








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67ocn-c5&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEdYWCEliqwsgAAAVRVSccdTem9_QAYSh_0tqIeSnpKiiwT4Kihvc3KEhXvwTq4duXx9XIpsI3ZjzKT-Oda4iLVp4W3L0KtZM_uTWuExf1k-XSFrK_M83hxBryfQ8c5dnwjgA7vO_VaBXg_Nw6uXeHdpjO0BNJFqvRNDroVfrMXiVHyF3Fe-5jaTlHSlcvLegr8&eid=0-ini67ocn-c5


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67ocn-c5&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
